name: pythonworkflow
on: workflow_dispatch
jobs:
  data_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up python 3.10
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
         
      - name: clean_data 
        run: |
          cd ModelCleaning
          python cleandata.py
          
      - name: Train and test model
        run: |
          cd ModelCleaning
          python train_and_test.py
     
