name: tutorial1
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Todays date is $(date) "

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step2
        run: echo " hellow from job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step 3
        run: echo "hello from job 3"
    
